language: go

go:
    - 1.6.2
    
addons:
    apt:
        packages:
            - sshpass

script:
    - sed "s/%% paste your developer key %%/$YoutubeAPIDeveloperKey/g" search/conf.go > tmp
    - mv tmp search/conf.go
    - go test -v ./...
    - go build


after_success:
    - sshpass -e scp -o StrictHostKeychecking=no minstrel-server $MinstrelDeployServerUserName@$MinstrelDeployServerHost:~
    - sshpass -e ssh -o StrictHostKeychecking=no $MinstrelDeployServerUserName@$MinstrelDeployServerHost ./minstrel-server&